In [5]:
from sklearn.svm import SVC
from sklearn.datasets import load_iris
iris = load_iris()
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [7]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [8]:
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[46:52]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
46                5.1               3.8                1.6               0.2   
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   

        flower  
46      setosa  
47      setosa  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, train_size=0.7)

In [10]:
model = SVC(kernel='rbf', C=30, gamma='auto')
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9777777777777777

In [11]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel='linear', C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [12]:
cross_val_score(SVC(kernel='rbf', C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [13]:
cross_val_score(SVC(kernel='rbf', C=20, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [14]:
kernels = ['rbf', 'linear']
C = [1,10,20]
for ker in kernels:
    for C_val in C:
        score = cross_val_score(SVC(kernel=ker, C=C_val, gamma='auto'), iris.data, iris.target, cv=5)
        avg_score = np.average(score)
        print('{}_{}: {}'.format(ker,C_val,avg_score))

rbf_1: 0.9800000000000001
rbf_10: 0.9800000000000001
rbf_20: 0.9666666666666668
linear_1: 0.9800000000000001
linear_10: 0.9733333333333334
linear_20: 0.9666666666666666


In [18]:
clf = GridSearchCV(SVC(gamma='auto'), {
    'C' : [1,10,20],
    'kernel' : ['rbf', 'linear']
}, cv=5, return_train_score=False)
clf.fit(iris.data, iris.target)
df = pd.DataFrame(clf.cv_results_)

In [20]:
df[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [21]:
clf.best_score_

0.9800000000000001

In [22]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

model_params = {
    'svm' : {
        'model' : SVC(gamma='auto'),
        'params' : {
            'C' : [1,10,20],
            'kernel' : ['rbf','linear']
        }
    },
    'randomforest' : {
        'model' : RandomForestClassifier(),
        'params' : {
            'n_estimators' : [1,5,10]
        }
    },
    'logistic_regression' : {
        'model' : LogisticRegression(solver='liblinear', multi_class='auto'),
        'params' : {
            'C' : [1,5,10]
        }
    }
}

In [32]:
scores = []
for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model' : model_name,
        'best_score' : clf.best_score_,
        'best_params' : clf.best_params_
    })
df = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1         randomforest    0.960000        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}

In [39]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import GridSearchCV
digits = load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [55]:
models_params = {
    'svm' : {
        'model' : SVC(gamma='auto'),
        'params' : {
            'C' : [1,10,20],
            'kernel' : ['linear','rbf']
        }
    },
    'randomforest' :{
        'model' : RandomForestClassifier(),
        'params' : {
            'n_estimators' : [1,5,10]
        }
    },
    'logistic_regression' : {
        'model' : LogisticRegression(solver='liblinear', multi_class='auto'),
        'params' : {
            'C' : [1,5,10]
        }
    },
    'descision_tree' : {
        'model' : DecisionTreeClassifier(random_state=42),
        'params' : {
            'max_depth': [10, 20, 30, None],
            'min_samples_split': [2, 5, 10],
            'min_samples_leaf': [1, 2, 4]
        }
    },
    'multinomial_NB' : {
        'model' : MultinomialNB(),
        'params' : {}
    },
    'gaussian_NB' : {
        'model' : GaussianNB(),
        'params' : {}
    }
}

In [57]:
result = []
for model_name, mp in models_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(digits.data, digits.target)
    result.append({
        'model' : model_name,
        'best score' : clf.best_score_,
        'best param' : clf.best_params_
    })

df = pd.DataFrame(result, columns=['model', 'best score', 'best param'])
df

model  best score  \
0                  svm    0.947697   
1         randomforest    0.892058   
2  logistic_regression    0.922114   
3       descision_tree    0.788572   
4       multinomial_NB    0.870350   
5           gussian_NB    0.806928   

                                          best param  
0                       {'C': 1, 'kernel': 'linear'}  
1                               {'n_estimators': 10}  
2                                           {'C': 1}  
3  {'max_depth': 10, 'min_samples_leaf': 1, 'min_...  
4                                                 {}  
5                                                 {}