In [34]:
import math
import numpy as np

In [2]:
#Activation Function
def sigmoid(x):
    return 1/(1+math.exp(-x))       #Output range: 0 to 1

def tanh(x):
    return (math.exp(x)-math.exp(-x))/(math.exp(x)+math.exp(-x))           #Output_range: -1 to 1

def relu(x):
    return max(0,x)

def leaky_relu(x):
    return max(0.1*x, x)

In [28]:
x = np.array([[180,200,220],[12,18,20],[24,36,40]])
y = np.array([[80,90,100],[10,16,20],[8,10,10]])
value_per_x = np.array([1000,400,1200])
print(value_per_x*x)
print(np.dot(value_per_x,x))
print(x+y)
print(x-y)

[[180000  80000 264000]
 [ 12000   7200  24000]
 [ 24000  14400  48000]]
[213600 250400 276000]
[[260 290 320]
 [ 22  34  40]
 [ 32  46  50]]
[[100 110 120]
 [  2   2   0]
 [ 16  26  30]]


In [35]:
# Mean absoulte error
y_pred = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

def mae(y_pred, y_true):
    total_error = 0
    for yp, yt in zip(y_pred, y_true):
        total_error += abs(yp-yt)
    print("total error is: ", total_error)
    mae = total_error/len(y_pred)
    print("Mean absolute error is: ", mae)
    return mae

mae(y_pred, y_true)

total error is:  2.5
Mean absolute error is:  0.5


np.float64(0.5)

In [38]:
# Absoulte mean error with Numpy
def mae_np(y_pred, y_true):
    return np.mean(np.abs(y_pred - y_true))

In [48]:
# Implement Log loss or Binary Cross Entropy
epsilon = 1e-15
def log_loss(y_pred, y_true):
    y_pred_new = [max(i, epsilon) for i in y_pred]
    y_pred_new = [min(i, 1-epsilon) for i in y_pred_new]
    y_pred_new = np.array(y_pred_new)
    log_loss = -np.mean(y_true * np.log(y_pred_new) + (1-y_true)*np.log(1-y_pred_new))
    return log_loss

In [49]:
log_loss(y_pred, y_true)

np.float64(17.2696280766844)

In [53]:
# Mean Squared Error
def MSE(y_pred, y_true):
    squared = 0
    for yp, yt in zip(y_pred, y_true):
        squared += (yp-yt)**2
    mse = squared/len(y_pred)
    return mse
print(MSE(y_pred, y_true))

0.366
